JOINERS = ['of',
           'for']

INSPIRATIONS = ['Uber',
                'Netflix',
                'iPhone',
                'Instagram',
                'Snapchat',
                'Facebook',
                'YouTube',
                'YCombinator',
                'Tesla',
                'SpaceX',
                'Google',
                'Tinder',
                'GitHub',
                'Fiverr',
                'Windows 10',
                'Dropbox',
                'Walmart',
                'Pornhub',
                'StackOverflow',
                'Amazon',
                'Tencent',
                'Wikipedia',
                'LinkedIn',
                'Bing',
                'Whole Foods']

MARKETS = ['weed',
           'baseball cards',
           'music discovery',
           'native advertising',
           'podcasts',
           'sheet music',
           'test answers',
           'cybersecurity',
           'millenial travel vloggers',
           'veganism',
           'fair-trade animal fur',
           'flour mills',
           'test answers',
           'preteens',
           'green energy',
           'laundry',
           'politicians',
           'healthcare',
           'guns',
           'restaurant reservations',
           'cold hard facts']
